name: ADMC CI

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build software using docker
    steps:
      - name: Checkout
        uses: actions/checkout@v2        
      - run: docker build . --file Dockerfile --tag build-environment
#       - run: docker run pwd && ls
      - run: docker run -i --log-driver=none -a stdin -a stdout -a stderr -v "$(pwd)":/app build-environment bash -c "pwd && ls"
#       "$(pwd)":/app build-environment
#       - run: docker run -i --log-driver=none -a stdin -a stdout -a stderr -v "$(pwd)":/app build-environment
