name: build

on:
  push:
  pull_request:
  workflow_run:
    workflows:
      - scheduled
    branches:
      - master
    types:
      - requested

jobs:
  Linux:
    runs-on: alt:p9

    steps:

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y qt5-base-devel cmake qt5-tools-devel qt5-tools libuuid-devel libsmbclient-devel libsasl2-devel catch2-devel doxygen glib2-devel libpcre-devel rpm-build gear libldap-devel libcmocka-devel libkrb5-devel samba-devel
    
    - name: Build
      run: |
        cmake .
        make -j12
